
========== INFERENCE ==========


Statistics
Min True : 355.257629
Max True : 457.968414
Min Pred : 355.257629
Max Pred : 457.968414
MAE      : 0.000000e+00
RMSE     : 0.000000e+00

Temperature Uniformity (|∇T|)
Mean |∇T| True : 3.207357e+00
Mean |∇T| Pred : 3.207357e+00
Max  |∇T| True : 9.055385e+00
Max  |∇T| Pred : 9.055385e+00
Std  |∇T| True : 2.013205e+00
Std  |∇T| Pred : 2.013205e+00
Gradient MAE   : 0.000000e+00
Gradient RMSE  : 0.000000e+00

Saved: C:\Users\aeghtesad\Desktop\BD\Talk with Peter\candidate_package\thermal_surrogate\Heat_Conduction_Surrogate\Sample_inference\inference_new_case.vtp
Log: C:\Users\aeghtesad\Desktop\BD\Talk with Peter\candidate_package\thermal_surrogate\Heat_Conduction_Surrogate\Sample_inference\inference.msg

Inference complete.
